apiVersion: v1
kind: Service
metadata:
  name: feedback-frontend-service
spec:
  selector:
    app: feedback-frontend
  ports:
    - protocol: TCP
      port: 80  # Der Service wird auf Port 80 verfügbar sein
      targetPort: 80  # Der Container-Port (in Pods) wird auch 80 sein
  type: LoadBalancer  # Ermöglicht den externen Zugriff auf die App
